development:
  adapter: postgresql
  encoding: unicode
  database: pfcsd

test:
  adapter: postgresql
  encoding: unicode
  database: pfcst

production:
  adapter: postgresql
  encoding: unicode
  database: pfcs
